### ISSUE TITLE
ToDo Roadmap

### ISSUE THREAD

**Issue by var3n1k** [var3n1k/Telegram-FormulaEGE#1]
# Features

### Module
- DataSet
  - Dictionary
    - FAQ
      - [ ] Add docs for editing FAQ dataset
    - Service
      - [ ] Add docs for editing Service dataset
    - Branch
      - [ ] Add docs for editing Branch dataset
    - Subject
      - [ ] Add docs for editing Subject dataset
    - Admin
      - [ ] Add docs for editing Admin dataset
### API
- Telegram
  - ChatBot
    - Messages
      - FAQ
        - [ ] Add docs for using messages handler to send FAQ question and receive answer on it
    - Commands
      - Slash
        - FAQ
          - [ ] Add docs for using `/faq` command
        - Pricing
          - [ ] Add docs for using `/pricing` command
        - Contacts
          - [ ] Add docs for using `/contacts` command
        - Registration
          - [ ] Add docs for using `/registration` command

### Module
- Types
  - FAQ
    - [ ] Add types for FAQ dataset
  - Service
    - [ ] Add types for Service dataset
  - Branch
    - [ ] Add types for Branch dataset
  - Subject
    - [ ] Add types for Subject dataset
  - Admin
    - [ ] Add types for Admin dataset
- DataSet
  - Dictionary
    - FAQ
      - [ ] Add FAQ dataset
    - Service
      - [ ] Add Service dataset
    - Branch
      - [ ] Add Branch dataset
    - Subject
      - [ ] Add Subject dataset
    - Admin
      - [ ] Add Admin dataset
### API
- Telegram
  - ChatBot
    - Messages
      - FAQ
        - [ ] Add messages handler to catch FAQ questions and throw answers on them
    - Commands
      - Slash
        - FAQ
          - [ ] Add `/faq` command
        - Pricing
          - [ ] Add `/pricing` command
        - Contacts
          - [ ] Add `/contacts` command
        - Registration
          - [ ] Add `/registration` command
