### ISSUE TITLE
ToDo Roadmap

### ISSUE THREAD

**Issue by var3n1k** [var3n1k/Telegram-FormulaEGE#1]
# Features

### Module
- DataSet
  - Dictionary
    - ~FAQ~
      - [ ] Add docs for editing FAQ dataset
    - ~Service~
      - [ ] Add docs for editing Service dataset
    - ~Branch~
      - [ ] Add docs for editing Branch dataset
    - ~Subject~
      - [ ] Add docs for editing Subject dataset
    - ~Admin~
      - [ ] Add docs for editing Admin dataset
### API
- Telegram
  - ChatBot
    - Messages
      - FAQ
        - [x] Add docs for using messages handler to send FAQ question and receive answer on it
    - Commands
      - Slash
        - FAQ
          - [x] Add docs for using `/faq` command
        - Pricing
          - [x] Add docs for using `/pricing` command
        - Contacts
          - [x] Add docs for using `/contacts` command
        - Registration
          - [x] Add docs for using `/registration` command

### Module
- Types
  - FAQ
    - [x] Add types for FAQ dataset
  - Service
    - [x] Add types for Service dataset
  - Branch
    - [x] Add types for Branch dataset
  - Subject
    - [x] Add types for Subject dataset
  - Admin
    - [x] Add types for Admin dataset
- DataSet
  - Dictionary
    - FAQ
      - [x] Add FAQ dataset
    - Service
      - [x] Add Service dataset
    - Branch
      - [x] Add Branch dataset
    - Subject
      - [x] Add Subject dataset
    - Admin
      - [x] Add Admin dataset
### API
- Telegram
  - ChatBot
    - Messages
      - FAQ
        - [x] Add messages handler to catch FAQ questions and throw answers on them
    - Commands
      - Slash
        - FAQ
          - [x] Add `/faq` command
        - Pricing
          - [x] Add `/pricing` command
        - Contacts
          - [x] Add `/contacts` command
        - Registration
          - [x] Add `/registration` command
